/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComecocosFrame.java
 *
 * Created on Feb 12, 2011, 10:02:09 PM
 */

package guicomecocos;
import data.*;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author isra
 */
public class ComecocosFrame extends javax.swing.JFrame {
    public static final int NUMERO_FANTASMAS=4;
    private Rejilla rejilla;
    private Comecocos c;
    private Mueve mueve;
    private Fantasma fantasmas[];

    /** Creates new form ComecocosFrame */
    public ComecocosFrame() {
        initComponents();
        setTitle("Comecocos");
        ImageIcon icono = new ImageIcon("./Imagen/icono.png");
        setIconImage(icono.getImage());
        rejilla=new Rejilla(31,28);
        c=new Comecocos(rejilla);
        fantasmas=new Fantasma[NUMERO_FANTASMAS];
        for(int i=0;i<NUMERO_FANTASMAS;i++){
            fantasmas[i]=new Fantasma(rejilla,i);
        }
        mueve=new Mueve(this,50,panelPuntuacion.getPuntuacion(),panelPuntuacion.getTiempo());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        botonNuevo = new javax.swing.JButton();
        botonPausa = new javax.swing.JButton();
        botonIniciar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        panelPuntuacion = new panelPuntuacion(this);
        tablero = new RejillaPanel(this);
        barraMenu = new javax.swing.JMenuBar();
        menuJuego = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panelBotones.setPreferredSize(new java.awt.Dimension(356, 50));
        panelBotones.setLayout(null);

        botonNuevo.setText("Nuevo Juego");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });
        panelBotones.add(botonNuevo);
        botonNuevo.setBounds(100, 10, 140, 27);

        botonPausa.setText("Pausa");
        botonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausaActionPerformed(evt);
            }
        });
        panelBotones.add(botonPausa);
        botonPausa.setBounds(250, 10, 80, 27);

        botonIniciar.setText("Iniciar");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        panelBotones.add(botonIniciar);
        botonIniciar.setBounds(10, 10, 80, 27);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panelBotones.add(botonSalir);
        botonSalir.setBounds(340, 10, 80, 27);

        getContentPane().add(panelBotones, java.awt.BorderLayout.NORTH);

        panelPuntuacion.setPreferredSize(new java.awt.Dimension(160, 259));

        javax.swing.GroupLayout panelPuntuacionLayout = new javax.swing.GroupLayout(panelPuntuacion);
        panelPuntuacion.setLayout(panelPuntuacionLayout);
        panelPuntuacionLayout.setHorizontalGroup(
            panelPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        panelPuntuacionLayout.setVerticalGroup(
            panelPuntuacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        getContentPane().add(panelPuntuacion, java.awt.BorderLayout.EAST);

        tablero.setPreferredSize(new java.awt.Dimension(480, 530));

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero);
        tablero.setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        getContentPane().add(tablero, java.awt.BorderLayout.CENTER);

        menuJuego.setMnemonic('F');
        menuJuego.setText("Juego");

        menuNuevo.setMnemonic('N');
        menuNuevo.setText("Nuevo");
        menuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoActionPerformed(evt);
            }
        });
        menuJuego.add(menuNuevo);

        menuSalir.setMnemonic('X');
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuJuego.add(menuSalir);

        barraMenu.add(menuJuego);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        inicializaJuego();
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        tablero.requestFocus();
        mueve.reanudar();
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausaActionPerformed
        tablero.requestFocus();
        if(mueve.getParado()){
            mueve.reanudar();
        }
        else{
            mueve.suspender();
        }
    }//GEN-LAST:event_botonPausaActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        tablero.requestFocus();
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            if(mueve.getParado()){
                mueve.reanudar();
            }
            else{
                mueve.suspender();
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        tablero.requestFocus();
    }//GEN-LAST:event_formMouseEntered

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        inicializaJuego();
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComecocosFrame().setVisible(true);
            }
        });
    }

    public Rejilla getRejilla(){
        return rejilla;
    }

    public Comecocos getComecocos(){
        return c;
    }

    public Fantasma[] getFantasmas(){
        return fantasmas;
    }

    public Mueve getMueve(){
        return mueve;
    }

    /**
    * Obtiene una referencia al panel donde se el tablero
    * @return una referencia al panel del juego
    */
    public RejillaPanel getPanel(){
        return tablero;
    }

    public panelPuntuacion getPanelPuntuacion(){
        return panelPuntuacion;
    }


    // Reanuda una partida iniciada anteriorme
    public void reanudarPartida(){
        for(int i=0;i<NUMERO_FANTASMAS;i++){
            fantasmas[i].initFantasma(rejilla,i);
        }
        c.initComecocos();
        panelPuntuacion.repaint();
        mueve.reanudar();
    }

    // Inicializa una partida nueva
    public void inicializaJuego(){
        rejilla.initRejilla();
        c.initComecocos();
        tablero.requestFocus();
        tablero.setDerrotado(false);
        tablero.repaint();
        for(int i=0;i<NUMERO_FANTASMAS;i++){
            fantasmas[i].initFantasma(rejilla, i);
        }
        panelPuntuacion.repaint();
        mueve.initMueve();
        mueve.reanudar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonPausa;
    private javax.swing.JButton botonSalir;
    private javax.swing.JMenu menuJuego;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panelBotones;
    private guicomecocos.panelPuntuacion panelPuntuacion;
    private guicomecocos.RejillaPanel tablero;
    // End of variables declaration//GEN-END:variables

}
