/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panelPuntuacion.java
 *
 * Created on Feb 22, 2011, 5:10:00 PM
 */

package guicomecocos;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author isra
 */
public class panelPuntuacion extends javax.swing.JPanel {
    private ComecocosFrame ventanaPrincipal;

    /** Creates new form panelPuntuacion */
    public panelPuntuacion() {
        initComponents();
    }

    public panelPuntuacion(ComecocosFrame vp){
        this();
        ventanaPrincipal=vp;
    }

    public JLabel getPuntuacion(){
        return puntuacion;
    }

    public JLabel getTiempo(){
        return tiempo;
    }

    // Dibuja las vidas disponibles en cada momento
    protected void paintComponent(java.awt.Graphics g){
        super.paintComponent(g);
        int n;
        //System.out.println("Repintando panel puntuacion");
        n=ventanaPrincipal.getMueve().getNumeroVidas();
        g.setColor(Color.YELLOW);
        int j=0;
        for(int i=1;i<=n;i++){
            g.fillArc(10+j,150, 20, 20, 45, 270);
            j+=30;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puntuacion = new javax.swing.JLabel();
        tiempo = new javax.swing.JLabel();
        vidas = new javax.swing.JLabel();

        setLayout(null);

        puntuacion.setText("Puntuacion = ");
        add(puntuacion);
        puntuacion.setBounds(10, 40, 140, 15);

        tiempo.setText("Tiempo = ");
        add(tiempo);
        tiempo.setBounds(10, 80, 120, 15);

        vidas.setText("Vidas restantes:");
        add(vidas);
        vidas.setBounds(10, 120, 130, 15);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel puntuacion;
    private javax.swing.JLabel tiempo;
    private javax.swing.JLabel vidas;
    // End of variables declaration//GEN-END:variables

}
